spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username:
    password:
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    showSql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect